import { Inter } from "@next/font/google";
import Head from "next/head";
import { useQueryCall } from "../utils/useQueryCall";

import { TicketCard } from "../components/card";

import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  const { data: tickets, isLoading } = useQueryCall({
    apiUrl: "http://localhost:5000/tickets",
    key: "tickets",
    reactQueryConfig: { retry: 2 },
  });

  console.log({ isLoading, data: tickets });

  return (
    <>
      {" "}
      <Head>
        <title>Ticket System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          {tickets?.map(({ ticketName, ticketDescription, id }: any) => (
            <TicketCard
              key={id}
              ticketName={ticketName}
              ticketDescription={ticketDescription}
              id={id}
            />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
